wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1673208589
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      4: 3.8.10
      5: 0.12.21
      8:
      - 5
data:
  desc: null
  value: /home/hamzakhan/Personal/github/yolov5/data/training_data.yaml
entity:
  desc: null
  value: firefly-balldetector
name:
  desc: null
  value: log dataset
project:
  desc: null
  value: firefly-ball-detector
resume:
  desc: null
  value: false
single_cls:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: true
